name: Benchmarks

on:
  push:
   branches:
    - main
  pull_request:

jobs:
  test:
    name: Benchmark library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 1.0.0-beta.11

      - name: Install bb
        run: |
          curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/master/barretenberg/bbup/install | bash
          echo "$HOME/.bb/" >> $GITHUB_PATH
          ~/.bb/bbup -nv 1.0.0-beta.9
          sudo apt install -y libc++-dev

      - name: Build Noir benchmark programs
        run: nargo export

      - name: Generate gates report
        run: ./scripts/build-gates-report.sh
        env:
          BACKEND: /home/runner/.bb/bb

      - name: Compare gates reports
        id: gates_diff
        uses: noir-lang/noir-gates-diff@dbe920a8dcc3370af4be4f702ca9cef29317bec1
        with:
          report: gates_report.json
          summaryQuantile: 0.9 # only display the 10% most significant circuit size diffs in the summary (defaults to 20%)

      - name: Add gates diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact circuit sizes
          delete: ${{ !steps.gates_diff.outputs.markdown }}
          message: ${{ steps.gates_diff.outputs.markdown }}
